pipeline_name: dp_robomimic
# env
env_name: lift_place
env_type: ph
abs_action: false
dataset_name: m84_low_dim
dataset_path: dev/robomimic/datasets/${env_name}/${dataset_name}.hdf5
mode: train
max_episode_steps: 500
obs_keys: ['object', 'robot0_eef_pos', 'robot0_eef_quat', 'robot0_gripper_qpos', 'robot0_joint_pos']
obs_dim: 30
action_dim: 7
obs_steps: 2
action_steps: 8
# train
device: cuda:0
seed: 0
num_workers: 12
gradient_steps: 300000
batch_size: 256
horizon: 10
nn: chi_transformer
diffusion: ddpm
sample_steps: 50
temperature: 1.0
# optimizer
lr: 0.000141
# eval
model_path: path/to/model
num_envs: 10
eval_episodes: 60
save_video: true
eval_freq: 25000
# log
exp_name: ${now:%Y.%m.%d-%H.%M}_${dataset_name}_${env_name}_${nn}_${diffusion}
save_path: logs # logs # train_tests
project: CleanDiffuser
group: dp_robomimic
wandb_mode: offline
log_freq: 2000
save_freq: 25000
work_dir: ${save_path}/${pipeline_name}/${mode}/${env_name}/${exp_name}_${now:%Y%m%d_%H%M%S}/${seed}
# resume
resume: True
resume_path: logs/dp_robomimic/train/lift_place/2025.06.25-19.46_m84_low_dim_lift_place_chi_transformer_ddpm_20250625_194640/42
resume_tag: model_final
# hydra
hydra:
  run:
    dir: ${work_dir}
  job:
    chdir: false



